apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    rollout-manager/devices: device-1,device-2,device-3,device-4,device-5
  labels:
    app: example-rollout
    rollout-id: 783ed87b-743b-47ce-9934-27b595e9ec2b
    rollout-manager: "true"
  name: 783ed87b-743b-47ce-9934-27b595e9ec2b
  namespace: default
spec:
  paused: true
  replicas: 1
  selector:
    matchLabels:
      app: example-rollout
  strategy:
    canary:
      steps:
      - setWeight: 5
      - analysis:
          args:
          - name: rollout-percentage
            value: "5"
          - name: device-subset
            value: '["device-1"]'
          templates:
          - templateName: rollout-analysis-783ed87b-743b-47ce-9934-27b595e9ec2b
      - pause:
          duration: 60m
      - setWeight: 20
      - pause:
          duration: 60m
      - setWeight: 50
      - analysis:
          args:
          - name: rollout-percentage
            value: "50"
          - name: device-subset
            value: '["device-2"]'
          templates:
          - templateName: rollout-analysis-783ed87b-743b-47ce-9934-27b595e9ec2b
      - pause:
          duration: 60m
      - setWeight: 100
      - analysis:
          args:
          - name: rollout-percentage
            value: "100"
          - name: device-subset
            value: '["device-3","device-4","device-5"]'
          templates:
          - templateName: rollout-analysis-783ed87b-743b-47ce-9934-27b595e9ec2b
  template:
    metadata:
      labels:
        app: example-rollout
    spec:
      containers:
      - env:
          CMS_BASE_URL: http://cms-service:8080
        image: curlimages/curl:latest
        name: example-rollout
