# AI Generated file
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    rollout-manager/devices: device-1,device-2,device-3,device-4,device-5
  labels:
    app: test-rollout
    rollout-id: f9fa47fd-3bc6-44b7-8e3a-15dd8d057064
    rollout-manager: "true"
  name: f9fa47fd-3bc6-44b7-8e3a-15dd8d057064
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-rollout
  strategy:
    canary:
      steps:
      - setWeight: 5
      - analysis:
          args:
          - name: rollout-percentage
            value: "5"
          - name: device-subset
            value: '["device-1"]'
          templates:
          - templateName: rollout-analysis-f9fa47fd-3bc6-44b7-8e3a-15dd8d057064
      - pause:
          duration: 60m
      - setWeight: 20
      - pause:
          duration: 60m
      - setWeight: 50
      - analysis:
          args:
          - name: rollout-percentage
            value: "50"
          - name: device-subset
            value: '["device-2"]'
          templates:
          - templateName: rollout-analysis-f9fa47fd-3bc6-44b7-8e3a-15dd8d057064
      - pause:
          duration: 60m
      - setWeight: 100
      - analysis:
          args:
          - name: rollout-percentage
            value: "100"
          - name: device-subset
            value: '["device-3","device-4","device-5"]'
          templates:
          - templateName: rollout-analysis-f9fa47fd-3bc6-44b7-8e3a-15dd8d057064
  template:
    metadata:
      labels:
        app: test-rollout
    spec:
      containers:
      - image: nginx:1.25-alpine
        name: test-rollout
        ports:
        - containerPort: 80
