# AI Generated file
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  annotations:
    rollout-manager/devices: device-1,device-2,device-3,device-4,device-5
    rollout-manager/templates: template-1,template-2
  labels:
    app: example-rollout
    rollout-id: 89907d7f-f2f4-4b2a-9341-b05d405d3555
    rollout-manager: "true"
  name: rollout-analysis-89907d7f-f2f4-4b2a-9341-b05d405d3555
  namespace: argo-rollouts
spec:
  args:
  - name: rollout-percentage
  - name: device-subset
  metrics:
  - count: 1
    failureCondition: result[0] == "failure"
    interval: 10s
    name: cms-validation
    provider:
      job:
        spec:
          backoffLimit: 2
          template:
            spec:
              containers:
              - args:
                - /bin/sh
                - -c
                - |2

                  HTTP_CODE=$(curl -s -w "%{http_code}" -o /tmp/response.txt \
                    -X POST "$CMS_BASE_URL$CMS_CONFIG_ROLLOUT_PATH" \
                    -H "Content-Type: application/json" \
                    -d @- <<EOF
                  {
                    "deviceIds": $DEVICES_JSON,
                    "rolloutName": "$ROLLOUT_ID",
                    "templateIds": $TEMPLATES_JSON
                  }
                  EOF
                  )

                  if [ "$HTTP_CODE" = "201" ]; then
                    echo "success"
                    exit 0
                  else
                    echo "failure: HTTP $HTTP_CODE"
                    cat /tmp/response.txt 2>/dev/null
                    exit 1
                  fi
                env:
                - name: ROLLOUT_ID
                  value: 89907d7f-f2f4-4b2a-9341-b05d405d3555
                - name: ROLLOUT_NAME
                  value: example-rollout
                - name: CMS_BASE_URL
                  value: http://mock-cms-service:8081
                - name: CMS_CONFIG_ROLLOUT_PATH
                  value: /api/configurations/devices/config-rollout
                - name: TEMPLATES_JSON
                  value: '["template-1","template-2"]'
                - name: DEVICES_JSON
                  value: '{{args.device-subset}}'
                - name: ROLLOUT_PERCENTAGE
                  value: '{{args.rollout-percentage}}'
                - name: CMS_BASE_URL
                  value: http://mock-cms-service:8081
                image: curlimages/curl:latest
                name: cms-validator
              restartPolicy: Never
    successCondition: result[0] == "success"
