# AI Generated file
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  annotations:
    rollout-manager/devices: device-001,device-002,device-003
  labels:
    app: My First Rollout
    rollout-id: 01KB28K68GTGK527KCS4JCDSNB
    rollout-manager: "true"
  name: rollout-analysis-01KB28K68GTGK527KCS4JCDSNB
  namespace: production
spec:
  args:
  - name: rollout-percentage
  - name: device-subset
  metrics:
  - count: 1
    failureCondition: result[0] == "failure"
    interval: 10s
    name: cms-validation
    provider:
      job:
        spec:
          backoffLimit: 2
          template:
            spec:
              containers:
              - args:
                - /bin/sh
                - -c
                - |2

                  HTTP_CODE=$(curl -s -w "%{http_code}" -o /tmp/response.txt \
                    -X POST "$CMS_BASE_URL$CMS_CONFIG_ROLLOUT_PATH" \
                    -H "Content-Type: application/json" \
                    -d @- <<EOF
                  {
                    "deviceIds": $DEVICES_JSON,
                    "rolloutName": "$ROLLOUT_ID",
                    "templateIds": $TEMPLATES_JSON
                  }
                  EOF
                  )

                  if [ "$HTTP_CODE" = "201" ]; then
                    echo "success"
                    exit 0
                  else
                    echo "failure: HTTP $HTTP_CODE"
                    cat /tmp/response.txt 2>/dev/null
                    exit 1
                  fi
                env:
                - name: ROLLOUT_ID
                  value: 01KB28K68GTGK527KCS4JCDSNB
                - name: ROLLOUT_NAME
                  value: My First Rollout
                - name: CMS_BASE_URL
                  value: https://cms.example.com
                - name: CMS_CONFIG_ROLLOUT_PATH
                  value: /api/configurations/devices/config-rollout
                - name: TEMPLATES_JSON
                  value: '["template-001"]'
                - name: DEVICES_JSON
                  value: '{{args.device-subset}}'
                - name: ROLLOUT_PERCENTAGE
                  value: '{{args.rollout-percentage}}'
                - name: CMS_BASE_URL
                  value: https://cms.example.com
                image: curlimages/curl:latest
                name: cms-validator
              restartPolicy: Never
    successCondition: result[0] == "success"
